name: myenv
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - pystan
  - fbprophet
  - numpy
  - pandas
  - streamlit
  - pip
  - pip:
      - --find-links https://download.pytorch.org/whl/torch_stable.html
      - neuralprophet
      - yfinance
      - streamlit-tags