name: myenv
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - pystan
  - fbprophet
  - numpy
  - pandas
  - streamlit
  - pip
  - pip:
      - yfinance
      - streamlit-tags