name: myenv
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.7
  - fbprophet
  - numpy
  - pandas
  - pip
  - pip:
      - yfinance
      - streamlit
      - streamlit-tags