name: stocks
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - fbprophet
  - pandas
  - numpy
  - matplotlib
  - jupyterlab
  - scikit-learn
  - pip
  - pip:
      - streamlit
      - yfinance